version: '3'

vars:
  BIN:
    sh: git rev-parse --show-toplevel
  APP_NAME:
    sh: basename $(git config --get remote.origin.url) .git

tasks:
  build:
    cmds:
      - go build -o "{{.BIN}}"/bin
  default:
    cmds:
      - echo "{{.DEFAULT_TASK}}"
    silent: false
    vars:
      DEFAULT_TASK: "default-task!"
